
#'Variant16x: Buzzier Bees' Common Configuration File | Game Version: 1.16.5
#'Variant16x: Buzzier Bees' Settings
[variant16x_buzzierbees]

	#General Settings
	#These options will OVERRIDE any Custom Settings!
	[variant16x_buzzierbees.general]
		#Enables/Disables ALL Pressure Plate Variants
		enablePressurePlates = true
		#Enables/Disables ALL Button Variants
		enableButtons = true
		#Enables/Disables ALL Miscellaneous Variants
		enableMiscellaneous = true

	#Custom Settings
	#These options allow for more in-depth configuring.
	[variant16x_buzzierbees.custom]

		#Custom Pressure Plate Settings
		[variant16x_buzzierbees.custom.pressurePlates]
			#Enables/Disables Honeycomb Pressure Plates Variants
			enableHoneycombPressurePlates = true

		#Custom Button Settings
		[variant16x_buzzierbees.custom.buttons]
			#Enables/Disables Honeycomb Button Variants
			enableHoneycombButtons = true

		#Custom Miscellaneous Settings
		[variant16x_buzzierbees.custom.miscellaneous]
			#Enables/Disables Scented Candle Variants
			#Requires 'enableSmallFlowers' in 'variant16x-common.toml' to be TRUE!
			enableScentedCandles = true

