
[General]
	#Sporers should only spawn in rain?
	sporerOnlySpawnInRain = true
	#Allowed mod biomes where the mobs can spawn, by ID like: minecraft, biomesoplenty, etc.
	modIDs = ["minecraft", "biomesoplenty", "omni", "betterendforge", "outer_end"]

["Cursed Skull spawn parameters"]
	cursedSkullBiomeDictionaries = ["OVERWORLD"]
	#Range: 0 ~ 32
	cursedSkullMinGroupSize = 1
	#Range: 0 ~ 32
	cursedSkullMaxGroupSize = 1
	#Range: 0 ~ 500
	cursedSkullWeight = 10

["Ender Beast spawn parameters"]
	#Range: 0 ~ 32
	enderBeastMinGroupSize = 1
	#Range: 0 ~ 32
	enderBeastMaxGroupSize = 1
	#Range: 0 ~ 500
	enderBeastWeight = 10
	enderBeastBiomeDictionaries = ["END"]

["Grand Rammer spawn parameters"]
	#Range: 0 ~ 500
	grandRammerWeight = 5
	grandRammerBiomeDictionaries = ["OVERWORLD"]
	#Range: 0 ~ 32
	grandRammerMinGroupSize = 1
	#Range: 0 ~ 32
	grandRammerMaxGroupSize = 1

["Ghoul spawn parameters"]
	#Range: 0 ~ 32
	ghoulMaxGroupSize = 4
	#Range: 0 ~ 32
	ghoulMinGroupSize = 2
	#Range: 0 ~ 500
	ghoulWeight = 100
	ghoulBiomeDictionaries = ["OVERWORLD"]

["Ice Elemental spawn parameters"]
	#Range: 0 ~ 32
	iceElementalMaxGroupSize = 2
	iceElementalBiomeDictionaries = ["SNOWY"]
	#Range: 0 ~ 500
	iceElementalWeight = 80
	#Range: 0 ~ 32
	iceElementalMinGroupSize = 1

["Jungle Golem spawn parameters"]
	#Range: 0 ~ 32
	jungleGolemMinGroupSize = 1
	jungleGolemBiomeDictionaries = ["JUNGLE"]
	#Range: 0 ~ 32
	jungleGolemMaxGroupSize = 1
	#Range: 0 ~ 500
	jungleGolemWeight = 5

["Magma Gulper spawn parameters"]
	#Range: 0 ~ 500
	magmaGulperWeight = 30
	magmaGulperBiomeDictionaries = ["NETHER"]
	#Range: 0 ~ 32
	magmaGulperMaxGroupSize = 1
	#Range: 0 ~ 32
	magmaGulperMinGroupSize = 1

["Magma Slime spawn parameters"]
	magmaSlimeBiomeDictionaries = ["NETHER"]
	#Range: 0 ~ 32
	magmaSlimeMinGroupSize = 1
	#Range: 0 ~ 500
	magmaSlimeWeight = 20
	#Range: 0 ~ 32
	magmaSlimeMaxGroupSize = 3

["Manhunter spawn parameters"]
	#Range: 0 ~ 32
	manhunterMinGroupSize = 1
	#Range: 0 ~ 32
	manhunterMaxGroupSize = 1
	#Range: 0 ~ 500
	manhunterWeight = 5
	manhunterBiomeDictionaries = ["OVERWORLD"]

["Mummy spawn parameters"]
	#Range: 0 ~ 32
	mummyMinGroupSize = 1
	#Range: 0 ~ 500
	mummyWeight = 10
	#Range: 0 ~ 32
	mummyMaxGroupSize = 1
	mummyBiomeDictionaries = ["SANDY"]

["Mundane Slime spawn parameters"]
	mundaneSlimeBiomeDictionaries = ["FOREST", "PLAINS"]
	#Range: 0 ~ 32
	mundaneSlimeMaxGroupSize = 4
	#Range: 0 ~ 32
	mundaneSlimeMinGroupSize = 1
	#Range: 0 ~ 500
	mundaneSlimeWeight = 40

["Nyctoid spawn parameters"]
	nyctoidBiomeDictionaries = ["OVERWORLD"]
	#Range: 0 ~ 32
	nyctoidMaxGroupSize = 1
	#Range: 0 ~ 32
	nyctoidMinGroupSize = 1
	#Range: 0 ~ 500
	nyctoidWeight = 0

["Possessed Armor spawn parameters"]
	#Range: 0 ~ 500
	possessedArmorWeight = 60
	#Range: 0 ~ 32
	possessedArmorMinGroupSize = 1
	possessedArmorBiomeDictionaries = ["OVERWORLD"]
	#Range: 0 ~ 32
	possessedArmorMaxGroupSize = 1

["Rammer spawn parameters"]
	#Range: 0 ~ 32
	rammerMinGroupSize = 1
	#Range: 0 ~ 500
	rammerWeight = 5
	rammerBiomeDictionaries = ["FOREST", "PLAINS"]
	#Range: 0 ~ 32
	rammerMaxGroupSize = 1

["Sporer spawn parameters"]
	#Range: 0 ~ 32
	sporerMaxGroupSize = 2
	sporerBiomeDictionaries = ["OVERWORLD"]
	#sporer only spawns when it's raining
	#Range: 0 ~ 32
	sporerMinGroupSize = 1
	#Range: 0 ~ 500
	sporerWeight = 10

