
#Server and Client side changes.
[common]
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 25
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 80
	#Disables the Looter's ability to take the player's weapon (This makes them spawn with a random weapon, good and bad)
	disableLooterStealing = true

	[common.small_house]
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.2
		#Spacing between structures
		#Range: > 1
		spacing = 15
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 5

	[common.farlander_village]
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.6
		#Spacing between structures
		#Range: > 1
		spacing = 32
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 15

