
["Overworld Spawning"]
	#Range: 0 ~ 200
	"Spawn Weight" = 50
	Enabled = true
	#Range: 0 ~ 10
	"Max Group Size" = 2

["Nether Spawning"]
	#Range: 0 ~ 100
	"Spawn Weight" = 30
	Enabled = true
	#Range: 0 ~ 10
	"Max Group Size" = 2

["End Spawning"]
	#Range: 0 ~ 100
	"Spawn Weight" = 5
	Enabled = true
	#Range: 0 ~ 10
	"Max Group Size" = 3

["Toggle Ender Pearl Sword Dropping"]
	#A false value will prevent the Lurker from dropping the Ender Pearl Sword.
	Enabled = false
	#Range: 0 ~ 1000
	"Drop Rate 1 in" = 150

