
[entities]

	[entities.moth]
		#Disables natural spawning
		doSpawning = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 10
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 3
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:tall_birch_forest", "minecraft:flower_forest", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:wooded_hills", "minecraft:giant_spruce_taiga", "minecraft:jungle_edge", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga", "minecraft:birch_forest", "minecraft:giant_tree_taiga", "minecraft:wooded_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills"]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 0

	[entities.hidebehind]
		#Disables natural spawning
		doSpawning = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 5
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:tall_birch_forest", "minecraft:flower_forest", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:wooded_hills", "minecraft:giant_spruce_taiga", "minecraft:jungle_edge", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga", "minecraft:birch_forest", "minecraft:giant_tree_taiga", "minecraft:wooded_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills"]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true
		#Setting to true enables biome based variant spawning. This will make this entity choose variants based on the biome they spawn in. (No longer affects spawn eggs as it did in the past, only natural spawns)
		biomeBasedVariants = true

	[entities.wisp]
		#Disables natural spawning
		doSpawning = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 13
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 3
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:tall_birch_forest", "minecraft:flower_forest", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:wooded_hills", "minecraft:giant_spruce_taiga", "minecraft:jungle_edge", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga", "minecraft:birch_forest", "minecraft:giant_tree_taiga", "minecraft:wooded_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills"]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true
		#Chance of wisp being hostile (soul stealer). Chance is 1/x, where x is the value specified. 0 is no chance, 1 is 100% chance, 2 is 50% chance, etc
		#Range: > 0
		hostile_chance = 8

	[entities.hirschgeist]
		#Disables natural spawning
		doSpawning = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 2
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:tall_birch_forest", "minecraft:flower_forest", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:wooded_hills", "minecraft:giant_spruce_taiga", "minecraft:jungle_edge", "minecraft:snowy_taiga_mountains", "minecraft:tall_birch_hills", "minecraft:taiga", "minecraft:birch_forest", "minecraft:giant_tree_taiga", "minecraft:wooded_mountains", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills"]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true

	[entities.zotzpyre]
		#Disables natural spawning
		doSpawning = true
		#The spawn chance compared to other entities (typically between 6-20)
		#Range: 1 ~ 9999
		weight = 30
		#Must be greater than 0
		#Range: 1 ~ 9999
		minGroup = 1
		#Must be greater or equal to min value!
		#Range: 1 ~ 9999
		maxGroup = 1
		#Whether to use spawn costs in spawning or not
		useSpawnCosts = false
		#Cost to spawning algorithm per entity spawned
		#Range: 0.01 ~ 9999.0
		costPer = 1.0
		#Maxmimum cost the spawning algorithm can accrue for this entity
		#Range: 0.01 ~ 9999.0
		maxCost = 10.0
		#Enter biome Resource Locations. Supports modded biomes.
		spawnBiomes = ["minecraft:jungle", "minecraft:modified_jungle_edge", "minecraft:flower_forest", "minecraft:taiga_hills", "minecraft:shattered_savanna", "minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:modified_gravelly_mountains", "minecraft:mountain_edge", "minecraft:wooded_hills", "minecraft:taiga", "minecraft:birch_forest", "minecraft:wooded_mountains", "minecraft:beach", "minecraft:forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:eroded_badlands", "minecraft:tall_birch_forest", "minecraft:modified_wooded_badlands_plateau", "minecraft:taiga_mountains", "minecraft:snowy_beach", "minecraft:modified_badlands_plateau", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:mountains", "minecraft:ice_spikes", "minecraft:modified_jungle", "minecraft:gravelly_mountains", "minecraft:shattered_savanna_plateau", "minecraft:giant_spruce_taiga", "minecraft:jungle_edge", "minecraft:desert_hills", "minecraft:snowy_taiga_mountains", "minecraft:stone_shore", "minecraft:tall_birch_hills", "minecraft:mushroom_field_shore", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "minecraft:jungle_hills", "minecraft:dark_forest_hills"]
		#True if this entity can despawn freely when no players are nearby.
		doDespawn = true

