
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:meadow_forest", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:alps_foothills", "biomesoplenty:shroomy_wetland", "biomesoplenty:mystic_grove", "biomesoplenty:tall_dead_forest", "biomesoplenty:seasonal_pumpkin_patch", "minecraft:flower_forest", "omni:flower_field", "biomesoplenty:woodland", "biomesoplenty:ominous_mire", "minecraft:swamp_hills", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:dark_forest_hills", "biomesoplenty:rainforest_floodplain", "minecraft:jungle_edge", "minecraft:birch_forest", "biomesoplenty:coniferous_lakes", "biomesoplenty:bayou", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_fir_clearing", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga", "biomesoplenty:fir_clearing", "minecraft:wooded_hills", "minecraft:birch_forest_hills", "biomesoplenty:wetland_forest", "biomesoplenty:dense_woodland", "biomesoplenty:seasonal_forest", "biomesoplenty:redwood_hills", "biomesoplenty:bayou_mangrove", "biomesoplenty:seasonal_orchard", "biomesoplenty:lavender_forest", "minecraft:taiga", "biomesoplenty:rainbow_hills", "biomesoplenty:highland_moor", "minecraft:tall_birch_forest", "minecraft:dark_forest", "biomesoplenty:burnt_forest", "minecraft:wooded_mountains", "biomesoplenty:muskeg", "minecraft:swamp", "minecraft:tall_birch_hills", "biomesoplenty:marsh", "biomesoplenty:orchard", "biomesoplenty:redwood_forest_edge", "biomesoplenty:bamboo_blossom_grove", "biomesoplenty:rainforest", "biomesoplenty:snowy_maple_forest", "minecraft:forest", "biomesoplenty:ominous_woods", "biomesoplenty:dense_marsh", "biomesoplenty:meadow", "minecraft:snowy_taiga_mountains", "biomesoplenty:jade_cliffs", "omni:tall_forest", "biomesoplenty:deep_bayou", "minecraft:snowy_taiga_hills", "minecraft:taiga_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:redwood_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:dead_forest", "biomesoplenty:wetland", "biomesoplenty:grove", "biomesoplenty:tundra_bog"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 8
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:meadow_forest", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:alps_foothills", "biomesoplenty:shroomy_wetland", "biomesoplenty:mystic_grove", "biomesoplenty:tall_dead_forest", "biomesoplenty:seasonal_pumpkin_patch", "minecraft:flower_forest", "omni:flower_field", "biomesoplenty:woodland", "biomesoplenty:ominous_mire", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:dark_forest_hills", "minecraft:jungle_edge", "minecraft:birch_forest", "biomesoplenty:coniferous_lakes", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_fir_clearing", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga", "biomesoplenty:fir_clearing", "minecraft:wooded_hills", "minecraft:birch_forest_hills", "biomesoplenty:wetland_forest", "biomesoplenty:dense_woodland", "biomesoplenty:seasonal_forest", "biomesoplenty:redwood_hills", "biomesoplenty:seasonal_orchard", "biomesoplenty:lavender_forest", "minecraft:taiga", "biomesoplenty:rainbow_hills", "minecraft:tall_birch_forest", "minecraft:dark_forest", "biomesoplenty:burnt_forest", "minecraft:wooded_mountains", "minecraft:tall_birch_hills", "biomesoplenty:orchard", "biomesoplenty:redwood_forest_edge", "biomesoplenty:bamboo_blossom_grove", "biomesoplenty:rainforest", "biomesoplenty:snowy_maple_forest", "minecraft:forest", "biomesoplenty:ominous_woods", "biomesoplenty:meadow", "minecraft:snowy_taiga_mountains", "biomesoplenty:jade_cliffs", "omni:tall_forest", "minecraft:snowy_taiga_hills", "minecraft:taiga_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:redwood_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:dead_forest", "biomesoplenty:wetland", "biomesoplenty:grove"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 12.5

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["twilightforest:dark_forest_center", "biomesoplenty:meadow_forest", "biomesoplenty:cherry_blossom_grove", "undergarden:smogstem_forest", "biomesoplenty:alps_foothills", "biomesoplenty:shroomy_wetland", "twilightforest:firefly_forest", "biomesoplenty:mystic_grove", "biomesoplenty:tall_dead_forest", "biomesoplenty:seasonal_pumpkin_patch", "twilightforest:dense_forest", "minecraft:flower_forest", "omni:flower_field", "biomesoplenty:woodland", "biomesoplenty:ominous_mire", "minecraft:swamp_hills", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:dark_forest_hills", "undergarden:gronglegrowth", "biomesoplenty:rainforest_floodplain", "twilightforest:mushroom_forest", "minecraft:jungle_edge", "minecraft:birch_forest", "undergarden:wigglewood_forest", "biomesoplenty:coniferous_lakes", "biomesoplenty:bayou", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_fir_clearing", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "undergarden:mushroom_bog", "minecraft:snowy_taiga", "biomesoplenty:fir_clearing", "minecraft:wooded_hills", "twilightforest:fire_swamp", "minecraft:birch_forest_hills", "biomesoplenty:wetland_forest", "minecraft:warped_forest", "biomesoplenty:dense_woodland", "biomesoplenty:seasonal_forest", "biomesoplenty:redwood_hills", "biomesoplenty:bayou_mangrove", "biomesoplenty:seasonal_orchard", "twilightforest:oak_savannah", "biomesoplenty:lavender_forest", "undergarden:dense_forest", "minecraft:taiga", "biomesoplenty:rainbow_hills", "twilightforest:highlands", "biomesoplenty:highland_moor", "minecraft:tall_birch_forest", "minecraft:dark_forest", "biomesoplenty:burnt_forest", "minecraft:wooded_mountains", "biomesoplenty:muskeg", "minecraft:swamp", "minecraft:tall_birch_hills", "twilightforest:enchanted_forest", "twilightforest:spooky_forest", "biomesoplenty:marsh", "biomesoplenty:orchard", "biomesoplenty:redwood_forest_edge", "biomesoplenty:bamboo_blossom_grove", "twilightforest:snowy_forest", "biomesoplenty:rainforest", "biomesoplenty:snowy_maple_forest", "minecraft:forest", "biomesoplenty:ominous_woods", "biomesoplenty:dense_marsh", "biomesoplenty:meadow", "twilightforest:forest", "minecraft:snowy_taiga_mountains", "twilightforest:dense_mushroom_forest", "biomesoplenty:jade_cliffs", "omni:tall_forest", "biomesoplenty:undergrowth", "biomesoplenty:deep_bayou", "minecraft:snowy_taiga_hills", "minecraft:taiga_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:redwood_forest", "biomesoplenty:snowy_coniferous_forest", "minecraft:crimson_forest", "biomesoplenty:dead_forest", "twilightforest:swamp", "biomesoplenty:wetland", "biomesoplenty:grove", "twilightforest:dark_forest", "biomesoplenty:tundra_bog"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:meadow_forest", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:alps_foothills", "biomesoplenty:shroomy_wetland", "biomesoplenty:mystic_grove", "biomesoplenty:tall_dead_forest", "biomesoplenty:seasonal_pumpkin_patch", "minecraft:flower_forest", "omni:flower_field", "biomesoplenty:woodland", "biomesoplenty:ominous_mire", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "minecraft:dark_forest_hills", "minecraft:jungle_edge", "minecraft:birch_forest", "biomesoplenty:coniferous_lakes", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_fir_clearing", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga", "biomesoplenty:fir_clearing", "minecraft:wooded_hills", "minecraft:birch_forest_hills", "biomesoplenty:wetland_forest", "biomesoplenty:dense_woodland", "biomesoplenty:seasonal_forest", "biomesoplenty:redwood_hills", "biomesoplenty:seasonal_orchard", "biomesoplenty:lavender_forest", "minecraft:taiga", "biomesoplenty:rainbow_hills", "minecraft:tall_birch_forest", "minecraft:dark_forest", "biomesoplenty:burnt_forest", "minecraft:wooded_mountains", "minecraft:tall_birch_hills", "biomesoplenty:orchard", "biomesoplenty:redwood_forest_edge", "biomesoplenty:bamboo_blossom_grove", "biomesoplenty:rainforest", "biomesoplenty:snowy_maple_forest", "minecraft:forest", "biomesoplenty:ominous_woods", "biomesoplenty:meadow", "minecraft:snowy_taiga_mountains", "biomesoplenty:jade_cliffs", "omni:tall_forest", "minecraft:snowy_taiga_hills", "minecraft:taiga_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:redwood_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:dead_forest", "biomesoplenty:wetland", "biomesoplenty:grove"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 30
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:gravel_beach", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:shroomy_wetland", "minecraft:shattered_savanna_plateau", "minecraft:modified_badlands_plateau", "biomesoplenty:mystic_grove", "biomesoplenty:wasteland", "biomesoplenty:tall_dead_forest", "minecraft:shattered_savanna", "biomesoplenty:tropics", "biomesoplenty:alps", "biomesoplenty:woodland", "biomesoplenty:ominous_mire", "minecraft:modified_wooded_badlands_plateau", "minecraft:dark_forest_hills", "biomesoplenty:bayou", "minecraft:snowy_tundra", "minecraft:giant_tree_taiga", "minecraft:mountains", "biomesoplenty:tundra_basin", "minecraft:modified_jungle_edge", "biomesoplenty:bayou_mangrove", "biomesoplenty:seasonal_orchard", "biomesoplenty:lavender_forest", "minecraft:taiga", "biomesoplenty:rainbow_hills", "biomesoplenty:fungal_field", "minecraft:dark_forest", "biomesoplenty:muskeg", "minecraft:swamp", "biomesoplenty:volcano", "biomesoplenty:redwood_forest_edge", "minecraft:stone_shore", "minecraft:gravelly_mountains", "biomesoplenty:highland_crag", "biomesoplenty:snowy_maple_forest", "omni:desert_jungle", "biomesoplenty:dense_marsh", "biomesoplenty:fungal_jungle", "minecraft:snowy_taiga_mountains", "biomesoplenty:tropic_beach", "omni:tall_forest", "biomesoplenty:shrubland_hills", "minecraft:desert_hills", "minecraft:taiga_hills", "biomesoplenty:coniferous_forest", "biomesoplenty:lush_desert", "biomesoplenty:flower_meadow", "biomesoplenty:redwood_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:mystic_plains", "biomesoplenty:grove", "biomesoplenty:tundra_bog", "biomesoplenty:highland", "biomesoplenty:lush_savanna", "biomesoplenty:meadow_forest", "biomesoplenty:dry_boneyard", "biomesoplenty:alps_foothills", "minecraft:snowy_beach", "projectvibrantjourneys:overgrown_spires", "omni:tropical_plains", "biomesoplenty:seasonal_pumpkin_patch", "minecraft:flower_forest", "omni:flower_field", "minecraft:jungle", "minecraft:modified_jungle", "biomesoplenty:volcanic_plains", "minecraft:swamp_hills", "minecraft:eroded_badlands", "minecraft:giant_spruce_taiga", "minecraft:taiga_mountains", "biomesoplenty:rainforest_floodplain", "projectvibrantjourneys:verdant_sands", "minecraft:jungle_edge", "minecraft:ice_spikes", "minecraft:birch_forest", "biomesoplenty:coniferous_lakes", "minecraft:giant_spruce_taiga_hills", "biomesoplenty:snowy_fir_clearing", "minecraft:giant_tree_taiga_hills", "minecraft:snowy_taiga", "biomesoplenty:fir_clearing", "minecraft:wooded_hills", "minecraft:birch_forest_hills", "biomesoplenty:lavender_field", "minecraft:modified_gravelly_mountains", "biomesoplenty:wetland_forest", "biomesoplenty:dense_woodland", "minecraft:jungle_hills", "minecraft:bamboo_jungle_hills", "biomesoplenty:seasonal_forest", "minecraft:mountain_edge", "biomesoplenty:redwood_hills", "minecraft:beach", "biomesoplenty:highland_moor", "minecraft:tall_birch_forest", "omni:badlands_jungle", "biomesoplenty:burnt_forest", "minecraft:wooded_mountains", "minecraft:tall_birch_hills", "biomesoplenty:marsh", "biomesoplenty:orchard", "minecraft:bamboo_jungle", "biomesoplenty:bamboo_blossom_grove", "biomesoplenty:rainforest", "minecraft:forest", "biomesoplenty:ominous_woods", "biomesoplenty:meadow", "biomesoplenty:jade_cliffs", "biomesoplenty:deep_bayou", "minecraft:snowy_taiga_hills", "minecraft:snowy_mountains", "minecraft:mushroom_field_shore", "biomesoplenty:rainforest_cliffs", "biomesoplenty:dead_forest", "biomesoplenty:wetland"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

