
#List of diet effects
[[effects]]

	[[effects.status_effects]]
		name = "minecraft:slowness"
		power = 3

	[[effects.status_effects]]
		name = "minecraft:weakness"
		power = 3

	[[effects.conditions]]
		groups = ["proteins", "grains", "fruits", "vegetables"]
		match = "any"
		above = 0.0
		below = 0.1

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:slowness"
		power = 2

	[[effects.status_effects]]
		name = "minecraft:weakness"
		power = 2

	[[effects.conditions]]
		groups = ["proteins", "grains", "fruits", "vegetables"]
		match = "any"
		above = 0.1
		below = 0.2

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:slowness"
		power = 1

	[[effects.status_effects]]
		name = "minecraft:weakness"
		power = 1

	[[effects.conditions]]
		groups = ["proteins", "grains", "fruits", "vegetables"]
		match = "any"
		above = 0.2
		below = 0.3

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:hunger"
		power = 0

	[[effects.status_effects]]
		name = "minecraft:nausea"
		power = 0

	[[effects.conditions]]
		groups = ["sugars"]
		match = "any"
		above = 0.7
		below = 0.8

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:hunger"
		power = 1

	[[effects.status_effects]]
		name = "minecraft:nausea"
		power = 1

	[[effects.conditions]]
		groups = ["sugars"]
		match = "any"
		above = 0.8
		below = 0.9

[[effects]]

	[[effects.status_effects]]
		name = "minecraft:hunger"
		power = 2

	[[effects.status_effects]]
		name = "minecraft:nausea"
		power = 2

	[[effects.conditions]]
		groups = ["sugars"]
		match = "any"
		above = 0.9
		below = 1.0

